/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import UtilityClasses.DBConnection;
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author B.M.D.C.Bandara
 */
public class CreateGRN extends javax.swing.JFrame {

    Home currHome;
    
    /**
     * Creates new form CreateGRN
     */
    public CreateGRN() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        setImg(new File("pics/backW.png"), lab_back);
    }

    CreateGRN(Home aThis) {
        this();
        currHome = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_supp_name = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txt_item_name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_unitprice = new javax.swing.JLabel();
        txt_buyprice = new javax.swing.JTextField();
        txt_unitprice1 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        txt_unitprice2 = new javax.swing.JLabel();
        txt_sellprice = new javax.swing.JTextField();
        lab_suppID = new javax.swing.JLabel();
        lab_itemid = new javax.swing.JLabel();
        txt_unitprice3 = new javax.swing.JLabel();
        txt_unitprice4 = new javax.swing.JLabel();
        txt_unitprice5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_unitprice6 = new javax.swing.JLabel();
        txt_unitprice7 = new javax.swing.JLabel();
        txt_payment = new javax.swing.JTextField();
        txt_grnTotal = new javax.swing.JTextField();
        txt_balance = new javax.swing.JTextField();
        lab_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        kGradientPanel1.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Create GRN");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(6, 6, 499, 74);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Supplier Name");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(110, 120, 150, 32);

        txt_supp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_supp_nameActionPerformed(evt);
            }
        });
        txt_supp_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_supp_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_supp_nameKeyReleased(evt);
            }
        });
        kGradientPanel1.add(txt_supp_name);
        txt_supp_name.setBounds(280, 120, 350, 32);

        jList2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList2KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        kGradientPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(280, 152, 350, 131);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Item Name");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(110, 160, 150, 32);

        txt_item_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_item_nameActionPerformed(evt);
            }
        });
        txt_item_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_item_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_item_nameKeyReleased(evt);
            }
        });
        kGradientPanel1.add(txt_item_name);
        txt_item_name.setBounds(280, 160, 350, 32);

        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        kGradientPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(280, 192, 350, 131);

        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM ID", "NAME", "BUYING PRICE", "SELLING PRICE", "QTY", "ITEM TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setIntercellSpacing(new java.awt.Dimension(2, 4));
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 300, 1210, 279);

        txt_unitprice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_unitprice.setText("Buying Price");
        kGradientPanel1.add(txt_unitprice);
        txt_unitprice.setBounds(110, 200, 150, 32);

        txt_buyprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buypriceActionPerformed(evt);
            }
        });
        txt_buyprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buypriceKeyPressed(evt);
            }
        });
        kGradientPanel1.add(txt_buyprice);
        txt_buyprice.setBounds(280, 200, 350, 32);

        txt_unitprice1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_unitprice1.setText("QTY");
        kGradientPanel1.add(txt_unitprice1);
        txt_unitprice1.setBounds(110, 240, 150, 32);

        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtyKeyPressed(evt);
            }
        });
        kGradientPanel1.add(txt_qty);
        txt_qty.setBounds(280, 240, 350, 32);

        txt_unitprice2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_unitprice2.setText("Item ID");
        kGradientPanel1.add(txt_unitprice2);
        txt_unitprice2.setBounds(720, 160, 150, 32);

        txt_sellprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sellpriceActionPerformed(evt);
            }
        });
        txt_sellprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sellpriceKeyPressed(evt);
            }
        });
        kGradientPanel1.add(txt_sellprice);
        txt_sellprice.setBounds(890, 200, 350, 32);

        lab_suppID.setBackground(new java.awt.Color(204, 204, 204));
        lab_suppID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lab_suppID.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lab_suppID.setOpaque(true);
        kGradientPanel1.add(lab_suppID);
        lab_suppID.setBounds(890, 120, 350, 32);

        lab_itemid.setBackground(new java.awt.Color(204, 204, 204));
        lab_itemid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lab_itemid.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lab_itemid.setOpaque(true);
        kGradientPanel1.add(lab_itemid);
        lab_itemid.setBounds(890, 160, 350, 32);

        txt_unitprice3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_unitprice3.setText("GRN Total");
        kGradientPanel1.add(txt_unitprice3);
        txt_unitprice3.setBounds(120, 610, 150, 32);

        txt_unitprice4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_unitprice4.setText("Payment");
        kGradientPanel1.add(txt_unitprice4);
        txt_unitprice4.setBounds(570, 610, 100, 32);

        txt_unitprice5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_unitprice5.setText("Balance");
        kGradientPanel1.add(txt_unitprice5);
        txt_unitprice5.setBounds(120, 660, 150, 32);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1);
        jButton1.setBounds(1070, 610, 212, 73);

        txt_unitprice6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_unitprice6.setText("Selling Price");
        kGradientPanel1.add(txt_unitprice6);
        txt_unitprice6.setBounds(720, 200, 150, 32);

        txt_unitprice7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_unitprice7.setText("Supplier ID");
        kGradientPanel1.add(txt_unitprice7);
        txt_unitprice7.setBounds(720, 120, 150, 32);

        txt_payment.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_payment.setForeground(new java.awt.Color(0, 102, 255));
        txt_payment.setText("0.0");
        txt_payment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_paymentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_paymentFocusLost(evt);
            }
        });
        txt_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paymentActionPerformed(evt);
            }
        });
        txt_payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_paymentKeyPressed(evt);
            }
        });
        kGradientPanel1.add(txt_payment);
        txt_payment.setBounds(680, 610, 220, 30);

        txt_grnTotal.setEditable(false);
        txt_grnTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_grnTotal.setForeground(new java.awt.Color(0, 102, 255));
        txt_grnTotal.setText("0.0");
        kGradientPanel1.add(txt_grnTotal);
        txt_grnTotal.setBounds(280, 610, 220, 30);

        txt_balance.setEditable(false);
        txt_balance.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_balance.setForeground(new java.awt.Color(255, 51, 51));
        txt_balance.setText("0.0");
        kGradientPanel1.add(txt_balance);
        txt_balance.setBounds(280, 660, 220, 30);

        lab_back.setText("jLabel4");
        lab_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab_backMouseExited(evt);
            }
        });
        kGradientPanel1.add(lab_back);
        lab_back.setBounds(1310, 10, 41, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_supp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_supp_nameActionPerformed
        if (!txt_supp_name.getText().trim().equals("")) {
            jList2.grabFocus();
            jList2.setSelectedIndex(0);
        }
    }//GEN-LAST:event_txt_supp_nameActionPerformed

    private void txt_item_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_item_nameActionPerformed
        if (!txt_item_name.getText().trim().equals("")) {
            jList1.grabFocus();
            jList1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_txt_item_nameActionPerformed

    private void txt_buypriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buypriceActionPerformed
        if (!txt_buyprice.getText().trim().equals("")) {
            txt_sellprice.grabFocus();
        }
    }//GEN-LAST:event_txt_buypriceActionPerformed

    private void txt_sellpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sellpriceActionPerformed
        if (!txt_sellprice.getText().trim().equals("")) {
            txt_qty.grabFocus();
        }
    }//GEN-LAST:event_txt_sellpriceActionPerformed

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        Vector v = new Vector();

        if (checkContents()) {
            if (checkAvailability()) {
                v.add(lab_itemid.getText());
                v.add(txt_item_name.getText());
                v.add(txt_buyprice.getText());
                v.add(txt_sellprice.getText());
                double qty = Double.valueOf(txt_qty.getText()) + previousQty;
                v.add(String.valueOf(qty));
                String itemTotal = String.valueOf(Double.parseDouble(txt_buyprice.getText()) * qty);
                v.add(itemTotal);
                dtm.addRow(v);
            } else {
                v.add(lab_itemid.getText());
                v.add(txt_item_name.getText());
                v.add(txt_buyprice.getText());
                v.add(txt_sellprice.getText());
                v.add(txt_qty.getText());
                String itemTotal = String.valueOf(Double.parseDouble(txt_buyprice.getText()) * Double.parseDouble(txt_qty.getText()));
                v.add(itemTotal);
                dtm.addRow(v);
            }
            clearFields();
            calculateGrnTotal();
        }
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void txt_buypriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buypriceKeyPressed
        if (Character.isDigit(evt.getKeyChar()) || (evt.getKeyChar() == '.' && !txt_buyprice.getText().contains("."))
                || evt.getKeyCode() == KeyEvent.VK_BACKSPACE || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_buyprice.setEditable(true);
        } else {
            txt_buyprice.setEditable(false);
        }
    }//GEN-LAST:event_txt_buypriceKeyPressed

    private void txt_sellpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sellpriceKeyPressed
        if (Character.isDigit(evt.getKeyChar()) || (evt.getKeyChar() == '.' && !txt_sellprice.getText().contains("."))
                || evt.getKeyCode() == KeyEvent.VK_BACKSPACE || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_sellprice.setEditable(true);
        } else {
            txt_sellprice.setEditable(false);
        }
    }//GEN-LAST:event_txt_sellpriceKeyPressed

    private void txt_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyPressed
        if (Character.isDigit(evt.getKeyChar()) || (evt.getKeyChar() == '.' && !txt_qty.getText().contains("."))
                || evt.getKeyCode() == KeyEvent.VK_BACKSPACE || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_qty.setEditable(true);
        } else {
            txt_qty.setEditable(false);
        }
    }//GEN-LAST:event_txt_qtyKeyPressed

    private void txt_supp_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_supp_nameKeyReleased
        try {
            ResultSet search = DBConnection.search("select * from supplier where name like '%" + txt_supp_name.getText().toLowerCase() + "%' and status=1");
            Vector v = new Vector();
            while (search.next()) {
                v.add(search.getString("name") + "\t-\t" + search.getString("id"));
            }
            jList2.setListData(v);
            jScrollPane3.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txt_supp_nameKeyReleased

    private void txt_item_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_nameKeyReleased
        try {
            ResultSet search = DBConnection.search("select * from item where name like '%" + txt_item_name.getText().toLowerCase() + "%' and status=1");
            Vector v = new Vector();
            while (search.next()) {
                v.add(search.getString("name") + "\t-\t" + search.getString("id"));
            }
            jList1.setListData(v);
            //jScrollPane2.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txt_item_nameKeyReleased

    private void jList2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_supp_name.setText(jList2.getSelectedValue().split("\t-\t")[0]);
            lab_suppID.setText(jList2.getSelectedValue().split("\t-\t")[1]);
            jScrollPane3.setVisible(false);
            txt_item_name.grabFocus();
        }
    }//GEN-LAST:event_jList2KeyPressed

    private void txt_supp_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_supp_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jList2.grabFocus();
            jList2.setSelectedIndex(0);
        }
    }//GEN-LAST:event_txt_supp_nameKeyPressed

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_item_name.setText(jList1.getSelectedValue().split("\t-\t")[0]);
            lab_itemid.setText(jList1.getSelectedValue().split("\t-\t")[1]);
            jScrollPane2.setVisible(false);
            txt_buyprice.grabFocus();
        }
    }//GEN-LAST:event_jList1KeyPressed

    private void txt_item_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jScrollPane2.setVisible(true);
            jList1.grabFocus();
            jList1.setSelectedIndex(0);
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            txt_payment.grabFocus();
        }
    }//GEN-LAST:event_txt_item_nameKeyPressed

    private void txt_paymentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_paymentFocusGained
        txt_payment.setText(null);
    }//GEN-LAST:event_txt_paymentFocusGained

    private void txt_paymentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_paymentFocusLost
        if (txt_payment.getText().equals("")) {
            txt_payment.setText("0.0");
        }
    }//GEN-LAST:event_txt_paymentFocusLost

    private void txt_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paymentActionPerformed
        txt_balance.setText(String.valueOf(Double.parseDouble(txt_payment.getText()) - Double.parseDouble(txt_grnTotal.getText())));
        jButton1.grabFocus();
    }//GEN-LAST:event_txt_paymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTable1.getRowCount() != 0) {
            int grnid = 0;
            int x = 0;
            try {
                DBConnection.iud("insert into grn(supplier_id,date,total,payment) values('" + lab_suppID.getText() + "', CURDATE() ,"
                        + "'" + txt_grnTotal.getText() + "','" + txt_payment.getText() + "')");
                ResultSet search = DBConnection.search("select id from grn");
                if (search.last()) {
                    grnid = search.getInt("id");
                }
                while (x < jTable1.getRowCount()) {
                    DBConnection.iud("insert into grn_item(grn_id,item_id,qty,unitprice,item_total) values('" + grnid + "',"
                            + "'" + Double.parseDouble(jTable1.getValueAt(x, 0).toString()) + "',"
                            + "'" + Double.parseDouble(jTable1.getValueAt(x, 4).toString()) + "',"
                            + "'" + Double.parseDouble(jTable1.getValueAt(x, 2).toString()) + "',"
                            + "'" + Double.parseDouble(jTable1.getValueAt(x, 5).toString()) + "')");
                    DBConnection.iud("update stock set qty=qty+" + Double.parseDouble(jTable1.getValueAt(x, 4).toString()) + ","
                            + "buying_price=" + Double.parseDouble(jTable1.getValueAt(x, 2).toString()) + ","
                            + "selling_price=" + Double.parseDouble(jTable1.getValueAt(x, 2).toString())
                            + " where item_id=" + Double.parseDouble(jTable1.getValueAt(x, 0).toString()) + "");
                    x++;
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            resetAll();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Add data first to save the GRN!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_paymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paymentKeyPressed
        if (Character.isDigit(evt.getKeyChar()) || (evt.getKeyChar() == '.' && !txt_payment.getText().contains("."))
                || evt.getKeyCode() == KeyEvent.VK_BACKSPACE || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_payment.setEditable(true);
        } else {
            txt_payment.setEditable(false);
        }
    }//GEN-LAST:event_txt_paymentKeyPressed

    private void lab_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_backMouseExited
        setImg(new File("pics/backW.png"), lab_back);
    }//GEN-LAST:event_lab_backMouseExited

    private void lab_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_backMouseEntered
        setImg(new File("pics/backB.png"), lab_back);
    }//GEN-LAST:event_lab_backMouseEntered

    private void lab_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_backMouseClicked
        this.setVisible(false);
        currHome.setVisible(true);
    }//GEN-LAST:event_lab_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateGRN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    public javax.swing.JLabel lab_back;
    private javax.swing.JLabel lab_itemid;
    private javax.swing.JLabel lab_suppID;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_buyprice;
    private javax.swing.JTextField txt_grnTotal;
    private javax.swing.JTextField txt_item_name;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_sellprice;
    private javax.swing.JTextField txt_supp_name;
    private javax.swing.JLabel txt_unitprice;
    private javax.swing.JLabel txt_unitprice1;
    private javax.swing.JLabel txt_unitprice2;
    private javax.swing.JLabel txt_unitprice3;
    private javax.swing.JLabel txt_unitprice4;
    private javax.swing.JLabel txt_unitprice5;
    private javax.swing.JLabel txt_unitprice6;
    private javax.swing.JLabel txt_unitprice7;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txt_item_name.setText(null);
        txt_buyprice.setText(null);
        txt_sellprice.setText(null);
        txt_qty.setText(null);
        lab_itemid.setText(null);
        txt_item_name.grabFocus();
    }

    double previousQty;

    private boolean checkAvailability() {
        String itemId = lab_itemid.getText().trim();
        int x = 0;
        boolean availability = false;
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        while (x < jTable1.getRowCount()) {
            if (jTable1.getValueAt(x, 0).toString().equals(itemId)) {
                availability = true;
                previousQty = Double.valueOf(jTable1.getValueAt(x, 4).toString());
                dtm.removeRow(x);
                break;
            } else {
                availability = false;
            }
            x++;
        }
        return availability;
    }

    private void calculateGrnTotal() {
        int x = 0;
        double grnTotal = 0;
        while (x < jTable1.getRowCount()) {
            grnTotal += Double.parseDouble(jTable1.getValueAt(x, 5).toString());
            x++;
        }
        txt_grnTotal.setText(String.valueOf(grnTotal));
    }

    private void resetAll() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        txt_supp_name.setText(null);
        lab_suppID.setText(null);
        clearFields();
        dtm.setRowCount(0);
        txt_grnTotal.setText("0.0");
        txt_payment.setText("0.0");
        txt_balance.setText("0.0");
        txt_supp_name.grabFocus();
    }
    
    private boolean contentChecked;
    
    private boolean checkContents() {
        if (txt_supp_name.getText().equals("")) {
            txt_supp_name.grabFocus();
            contentChecked = false;
        } else if (txt_item_name.getText().equals("")) {
            txt_item_name.grabFocus();
            contentChecked = false;
        } else if (txt_buyprice.getText().equals("") || txt_buyprice.getText().length() == 0) {
            txt_buyprice.grabFocus();
            contentChecked = false;
        } else if (txt_sellprice.getText().equals("") || txt_sellprice.getText().length() == 0) {
            txt_sellprice.grabFocus();
            contentChecked = false;
        }else if (txt_qty.getText().equals("") || txt_qty.getText().length() == 0) {
            txt_qty.grabFocus();
            contentChecked = false;
        } else {
            contentChecked = true;
        }
        return contentChecked;
    }
    
    private void setImg(File f, JLabel lab){
        try {
            Image img = ImageIO.read(f);
            img = img.getScaledInstance(lab.getWidth(), lab.getHeight(), Image.SCALE_SMOOTH);
            lab.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
