/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author B.M.D.C.Bandara
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setInitData();
    }

    CustomerManagement cusM = new CustomerManagement(this);
    ProductManagement proM = new ProductManagement(this);
    SupplierManagement suppM = new SupplierManagement(this);
    CreateGRN grn = new CreateGRN(this);
    CreateInvoice inv = new CreateInvoice(this);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lab_logo = new javax.swing.JLabel();
        lab_back = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        kGradientPanel1.setLayout(null);

        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseExited(evt);
            }
        });
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Supplier");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 184, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Management");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, 184, -1));

        jLabel16.setText("jLabel16");
        jLayeredPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 155, 146));

        jLabel12.setText("jLabel11");
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 95, 184, 231));

        kGradientPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(357, 270, 198, 368);

        jLayeredPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane2MouseExited(evt);
            }
        });
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Customer");
        jLayeredPane2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 184, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Management");
        jLayeredPane2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, 184, -1));

        jLabel17.setText("jLabel16");
        jLayeredPane2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 155, 146));

        jLabel13.setText("jLabel11");
        jLayeredPane2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 95, 184, 231));

        kGradientPanel1.add(jLayeredPane2);
        jLayeredPane2.setBounds(573, 270, 198, 368);

        jLayeredPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane3MouseExited(evt);
            }
        });
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product");
        jLayeredPane3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 184, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Management");
        jLayeredPane3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, 184, -1));

        jLabel20.setText("jLabel16");
        jLayeredPane3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 155, 146));

        jLabel11.setText("jLabel11");
        jLayeredPane3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 95, 184, 231));

        kGradientPanel1.add(jLayeredPane3);
        jLayeredPane3.setBounds(141, 270, 198, 368);

        jLayeredPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane4MouseExited(evt);
            }
        });
        jLayeredPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create");
        jLayeredPane4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 184, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GRN");
        jLayeredPane4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, 184, -1));

        jLabel19.setText("jLabel16");
        jLayeredPane4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 155, 146));

        jLabel15.setText("jLabel11");
        jLayeredPane4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 95, 184, 231));

        kGradientPanel1.add(jLayeredPane4);
        jLayeredPane4.setBounds(1027, 270, 198, 368);

        jLayeredPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane5MouseExited(evt);
            }
        });
        jLayeredPane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Create");
        jLayeredPane5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 184, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Invoice");
        jLayeredPane5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, 184, -1));

        jLabel18.setText("jLabel16");
        jLayeredPane5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 155, 146));

        jLabel14.setText("jLabel11");
        jLayeredPane5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 95, 184, 231));

        kGradientPanel1.add(jLayeredPane5);
        jLayeredPane5.setBounds(789, 270, 198, 368);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TRANS STORES");
        kGradientPanel1.add(jLabel21);
        jLabel21.setBounds(610, 100, 390, 60);

        lab_logo.setText("jLabel22");
        kGradientPanel1.add(lab_logo);
        lab_logo.setBounds(400, 80, 200, 80);

        lab_back.setText("jLabel4");
        lab_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab_backMouseExited(evt);
            }
        });
        kGradientPanel1.add(lab_back);
        lab_back.setBounds(1300, 710, 41, 40);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Copyright  ©   2021 HyTRANS. All Rights Reserved");
        kGradientPanel1.add(jLabel22);
        jLabel22.setBounds(20, 740, 330, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLayeredPane3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane3MouseEntered
        jLayeredPane3.setOpaque(true);
        jLayeredPane3.setBackground(Color.WHITE);
        jLabel1.setForeground(Color.DARK_GRAY);
        jLabel6.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLayeredPane3MouseEntered

    private void jLayeredPane3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane3MouseExited
        jLayeredPane3.setOpaque(false);
        jLayeredPane3.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        jLabel1.setForeground(Color.white);
        jLabel6.setForeground(Color.white);
    }//GEN-LAST:event_jLayeredPane3MouseExited

    private void jLayeredPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseEntered
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setBackground(Color.WHITE);
        jLabel2.setForeground(Color.DARK_GRAY);
        jLabel7.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLayeredPane1MouseEntered

    private void jLayeredPane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseExited
        jLayeredPane1.setOpaque(false);
        jLayeredPane1.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        jLabel2.setForeground(Color.white);
        jLabel7.setForeground(Color.white);
    }//GEN-LAST:event_jLayeredPane1MouseExited

    private void jLayeredPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane2MouseEntered
        jLayeredPane2.setOpaque(true);
        jLayeredPane2.setBackground(Color.WHITE);
        jLabel3.setForeground(Color.DARK_GRAY);
        jLabel8.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLayeredPane2MouseEntered

    private void jLayeredPane2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane2MouseExited
        jLayeredPane2.setOpaque(false);
        jLayeredPane2.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        jLabel3.setForeground(Color.white);
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_jLayeredPane2MouseExited

    private void jLayeredPane5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane5MouseEntered
        jLayeredPane5.setOpaque(true);
        jLayeredPane5.setBackground(Color.WHITE);
        jLabel4.setForeground(Color.DARK_GRAY);
        jLabel9.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLayeredPane5MouseEntered

    private void jLayeredPane5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane5MouseExited
        jLayeredPane5.setOpaque(false);
        jLayeredPane5.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        jLabel4.setForeground(Color.white);
        jLabel9.setForeground(Color.white);
    }//GEN-LAST:event_jLayeredPane5MouseExited

    private void jLayeredPane4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane4MouseEntered
        jLayeredPane4.setOpaque(true);
        jLayeredPane4.setBackground(Color.WHITE);
        jLabel5.setForeground(Color.DARK_GRAY);
        jLabel10.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLayeredPane4MouseEntered

    private void jLayeredPane4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane4MouseExited
        jLayeredPane4.setOpaque(false);
        jLayeredPane4.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        jLabel5.setForeground(Color.white);
        jLabel10.setForeground(Color.white);
    }//GEN-LAST:event_jLayeredPane4MouseExited

    private void jLayeredPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane3MouseClicked
        proM.setVisible(true);
    }//GEN-LAST:event_jLayeredPane3MouseClicked

    private void jLayeredPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseClicked
        suppM.setVisible(true);
    }//GEN-LAST:event_jLayeredPane1MouseClicked

    private void jLayeredPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane2MouseClicked
        cusM.setVisible(true);
    }//GEN-LAST:event_jLayeredPane2MouseClicked

    private void jLayeredPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane5MouseClicked
        inv.setVisible(true);
    }//GEN-LAST:event_jLayeredPane5MouseClicked

    private void jLayeredPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane4MouseClicked
        grn.setVisible(true);
    }//GEN-LAST:event_jLayeredPane4MouseClicked

    private void lab_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_backMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lab_backMouseClicked

    private void lab_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_backMouseEntered
        setImg(new File("pics/exitR.png"), lab_back);
    }//GEN-LAST:event_lab_backMouseEntered

    private void lab_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_backMouseExited
        setImg(new File("pics/exitW.png"), lab_back);
    }//GEN-LAST:event_lab_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private keeptoo.KGradientPanel kGradientPanel1;
    public javax.swing.JLabel lab_back;
    private javax.swing.JLabel lab_logo;
    // End of variables declaration//GEN-END:variables

    private void setImg(File f, JLabel lab){
        try {
            Image img = ImageIO.read(f);
            img = img.getScaledInstance(lab.getWidth(), lab.getHeight(), Image.SCALE_SMOOTH);
            lab.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private void setInitData() {
        setImg(new File("pics/exitW.png"), lab_back);
        setImg(new File("pics/butBack.png"), jLabel11);
        setImg(new File("pics/butBack.png"), jLabel12);
        setImg(new File("pics/butBack.png"), jLabel13);
        setImg(new File("pics/butBack.png"), jLabel14);
        setImg(new File("pics/butBack.png"), jLabel15);
        setImg(new File("pics/prod.png"), jLabel20);
        setImg(new File("pics/supp.png"), jLabel16);
        setImg(new File("pics/cus.png"), jLabel17);
        setImg(new File("pics/grn.png"), jLabel18);
        setImg(new File("pics/invoice.png"), jLabel19);
        setImg(new File("pics/logo.png"), lab_logo);
    }
}
